image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp *.md public/
    - cp -r src public/src
    - cp bb.edn public/
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
